//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int ID { get; set; }
        public string OldState { get; set; }
        public string NewState { get; set; }
        public string Command { get; set; }
    }
}
