//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string Task { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TaskHours { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
